import { NextResponse } from "next/server";
import { prisma } from "@/lib/db";

// GET - List purchase orders
export async function GET(request: Request) {
    try {
        const { searchParams } = new URL(request.url);
        const status = searchParams.get("status");

        const where: Record<string, unknown> = {};
        if (status) where.status = status;

        const orders = await prisma.purchaseOrder.findMany({
            where,
            include: {
                supplier: { select: { name: true } },
                items: true,
            },
            orderBy: { createdAt: "desc" },
        });
        return NextResponse.json(orders);
    } catch (error) {
        console.error("PO fetch error:", error);
        return NextResponse.json({ error: "Failed to fetch purchase orders" }, { status: 500 });
    }
}

// POST - Create purchase order
export async function POST(request: Request) {
    try {
        const data = await request.json();
        const orderNumber = `PO-${Date.now().toString(36).toUpperCase()}`;

        const po = await prisma.purchaseOrder.create({
            data: {
                orderNumber,
                supplierId: data.supplierId,
                status: data.status || "draft",
                totalAmount: data.totalAmount || 0,
                notes: data.notes,
                expectedDate: data.expectedDate ? new Date(data.expectedDate) : null,
                isAutoGenerated: data.isAutoGenerated || false,
                items: {
                    create: (data.items || []).map((item: { productName: string; sku: string; quantity: number; unitCost: number }) => ({
                        productName: item.productName,
                        sku: item.sku,
                        quantity: item.quantity,
                        unitCost: item.unitCost,
                        totalCost: item.quantity * item.unitCost,
                    })),
                },
            },
            include: { supplier: true, items: true },
        });

        return NextResponse.json(po, { status: 201 });
    } catch (error) {
        console.error("PO create error:", error);
        return NextResponse.json({ error: "Failed to create purchase order" }, { status: 500 });
    }
}

// PUT - Update purchase order (e.g., mark as received)
export async function PUT(request: Request) {
    try {
        const data = await request.json();
        const { id, ...updateData } = data;
        if (!id) return NextResponse.json({ error: "PO ID required" }, { status: 400 });

        // If marking as received, update inventory
        if (updateData.status === "received") {
            const po = await prisma.purchaseOrder.findUnique({
                where: { id },
                include: { items: true },
            });

            if (po) {
                for (const item of po.items) {
                    const inventory = await prisma.inventory.findUnique({ where: { sku: item.sku } });
                    if (inventory) {
                        await prisma.inventory.update({
                            where: { id: inventory.id },
                            data: {
                                quantity: { increment: item.quantity },
                                lastRestocked: new Date(),
                            },
                        });
                        await prisma.stockMovement.create({
                            data: {
                                inventoryId: inventory.id,
                                type: "in",
                                quantity: item.quantity,
                                reason: "Purchase order received",
                                reference: po.orderNumber,
                            },
                        });
                    }
                }
            }
            updateData.receivedDate = new Date();
        }

        const updated = await prisma.purchaseOrder.update({
            where: { id },
            data: updateData,
            include: { supplier: true, items: true },
        });

        return NextResponse.json(updated);
    } catch (error) {
        console.error("PO update error:", error);
        return NextResponse.json({ error: "Failed to update purchase order" }, { status: 500 });
    }
}
