export const dynamic = 'force-dynamic';
import { NextResponse } from "next/server";
import { zohoFetch, isZohoConnected } from "@/lib/zoho";
import { prisma } from "@/lib/db";

// GET - List purchase orders (from Zoho or local fallback)
export async function GET() {
    try {
        const connected = await isZohoConnected();

        if (connected) {
            const res = await zohoFetch("/purchaseorders");
            const data = await res.json();
            const purchaseorders = data.purchaseorders || [];

            const orders = purchaseorders.map((po: any) => ({
                id: po.purchaseorder_id,
                orderNumber: po.purchaseorder_number,
                status: po.status || "draft",
                totalAmount: po.total || 0,
                notes: po.notes || null,
                expectedDate: po.expected_delivery_date || null,
                receivedDate: po.delivery_date || null,
                isAutoGenerated: false,
                createdAt: po.created_time,
                updatedAt: po.last_modified_time,
                supplier: {
                    id: po.vendor_id,
                    name: po.vendor_name,
                },
                items: (po.line_items || []).map((item: any) => ({
                    id: item.line_item_id,
                    productName: item.name,
                    sku: item.sku || "",
                    quantity: item.quantity,
                    unitCost: item.rate,
                    totalCost: item.item_total,
                    receivedQty: item.quantity_received || 0,
                })),
            }));

            return NextResponse.json({ purchaseOrders: orders, source: "zoho" });
        }

        // Fallback: local database
        const purchaseOrders = await prisma.purchaseOrder.findMany({
            include: {
                supplier: { select: { id: true, name: true } },
                items: true,
            },
            orderBy: { createdAt: "desc" },
        });

        return NextResponse.json({ purchaseOrders, source: "local" });
    } catch (error) {
        console.error("Purchase orders fetch error:", error);
        return NextResponse.json({ error: "Failed to fetch purchase orders" }, { status: 500 });
    }
}

// POST - Create purchase order
export async function POST(request: Request) {
    try {
        const connected = await isZohoConnected();
        const data = await request.json();

        if (connected) {
            const res = await zohoFetch("/purchaseorders", {
                method: "POST",
                body: JSON.stringify({
                    vendor_id: data.supplierId,
                    line_items: (data.items || []).map((item: any) => ({
                        item_id: item.itemId,
                        quantity: item.quantity,
                        rate: item.unitCost,
                    })),
                    notes: data.notes,
                }),
            });
            const result = await res.json();
            return NextResponse.json(result, { status: 201 });
        }

        // Fallback: local database
        const orderNumber = `PO-${Date.now()}`;
        const po = await prisma.purchaseOrder.create({
            data: {
                orderNumber,
                supplierId: data.supplierId,
                status: "draft",
                totalAmount: data.totalAmount || 0,
                notes: data.notes,
                items: {
                    create: (data.items || []).map((item: any) => ({
                        productName: item.productName,
                        sku: item.sku,
                        quantity: item.quantity,
                        unitCost: item.unitCost,
                        totalCost: item.quantity * item.unitCost,
                    })),
                },
            },
            include: { supplier: true, items: true },
        });

        return NextResponse.json(po, { status: 201 });
    } catch (error) {
        console.error("Purchase order create error:", error);
        return NextResponse.json({ error: "Failed to create purchase order" }, { status: 500 });
    }
}
